mdapi-source/updated-package/objects/API_Routing__mdt.object
<CustomObject>
    <description>This metadata defines what URLs can be called and what class will process the request posted to that URL</description>
    <label>API Routing</label>
    <pluralLabel>API Routings</pluralLabel>
    <fields>
        <fullName>API_URL__c</fullName>
        <description>Defines the API URL that can called by an external application.
The format is the defined base URL for the Apex REST API (for example /apigateway/v1/) + a specific destination like import.
Put together the value would be: /apigateway/v1/import</description>
        <label>API URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the route is active or not. When inactive the route will not be checked.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Http_Method__c</fullName>
        <description>The Http method that can be used with the API URL</description>
        <label>Http Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DELETE</fullName>
                    <default>true</default>
                    <label>DELETE</label>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Classname__c</fullName>
        <description>This field contains the classname of the class that will process the import message that is received at this url.
The class needs to import the Import_Service_Base class.</description>
        <label>Service Classname</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/API_Route_Metadata_DataFactory_Test.cls
@IsTest
public class API_Route_Metadata_DataFactory_Test {

    // Create routing custom metadata in memory for testing
    public static List<API_Routing__mdt> createTestRoutes(){
    	List<API_Routing__mdt> routings = new List<API_Routing__mdt>();
        routings.add(new API_Routing__mdt(Active__c=true, API_URL__c='/IntServ/v1/import',Http_Method__c='POST', Service_Classname__c='Import_Service_Stub'));
        routings.add(new API_Routing__mdt(Active__c=true, API_URL__c='/IntServ/v1/import',Http_Method__c='GET', Service_Classname__c='Import_Service_Stub'));
        routings.add(new API_Routing__mdt(Active__c=true, API_URL__c='/IntServ/v1/import',Http_Method__c='PUT', Service_Classname__c='Import_Service_Stub'));
        routings.add(new API_Routing__mdt(Active__c=true, API_URL__c='/IntServ/v1/import',Http_Method__c='DELETE', Service_Classname__c='Import_Service_Stub'));
        return routings;
    }
}