mdapi-source/updated-package/objects/API_Routing__mdt.object
<CustomObject>
    <description>This metadata defines what URLs can be called and what class will process the request posted to that URL</description>
    <label>API Routing</label>
    <pluralLabel>API Routings</pluralLabel>
    <fields>
        <fullName>API_URL__c</fullName>
        <description>Defines the API URL that can called by an external application.
The format is the defined base URL for the Apex REST API (for example /apigateway/v1/) + a specific destination like import.
Put together the value would be: /apigateway/v1/import</description>
        <label>API URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the route is active or not. When inactive the route will not be checked.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Http_Method__c</fullName>
        <description>The Http method that can be used with the API URL</description>
        <label>Http Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DELETE</fullName>
                    <default>true</default>
                    <label>DELETE</label>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Classname__c</fullName>
        <description>This field contains the classname of the class that will process the import message that is received at this url.
The class needs to import the Import_Service_Base class.</description>
        <label>Service Classname</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Field__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in a section of an import message will be mapped to what Salesforce field.</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the mapping will be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapping_Object__c</fullName>
        <label>Mapping Object</label>
        <referenceTo>Mapping_Object__mdt</referenceTo>
        <relationshipLabel>Mapping Fields</relationshipLabel>
        <relationshipName>Mapping_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field contains the node in the import message that will be saved in Salesforce</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <description>This field contains the Salesforce field where the node will be saved.</description>
        <label>Salesforce Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transformation_Classname__c</fullName>
        <description>This field contains the classname of the class that will transform a field from the import message payload.
The class needs to import the interface Import_Field_Transformation_Interface.</description>
        <label>Transformation Classname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Object__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in an import message will be mapped to what Salesforce object.</description>
    <label>Mapping Object</label>
    <pluralLabel>Mapping Objects</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the mapping will be used</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field maps a node that contains sub node(s) to a Salesforce object</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.</description>
        <label>Message Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_External_Id_Field__c</fullName>
        <description>The name of the external id field that needs to be used when doing the upsert.</description>
        <label>Salesforce External Id Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>This field  shows that what Salesforce object the Message Payload Node will be mapped</description>
        <label>Salesforce Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Import_TestMetadataFactory.cls
@IsTest
public class Import_TestMetadataFactory {
    
    public class ConvertCaseOrigin implements Import_Field_Transformation_Interface {
        public Object transformValue(Object value) {
            string returnValue;
            if (value == 'TOCONVERT'){
                returnValue = 'Email';
            }
            return returnValue;
        }
    }
    
    // Create routing custom metadata in memory for testing
    public static List<API_Routing__mdt> createTestRoutes(){
    	List<API_Routing__mdt> routings = new List<API_Routing__mdt>();
        routings.add(new API_Routing__mdt(Active__c=true, API_URL__c='/apigateway/v1/import',Http_Method__c='POST', Service_Classname__c='Import_Service_Stub'));
        return routings;
    }
    
    // Create a mapping object that does not link to a Salesforce field
    public static List<Mapping_Object__mdt> createExcpetionMappingObjectsAndFields(){
        List<Mapping_Object__mdt> mappingObjects = new List<Mapping_Object__mdt>();

        // Create mapping for lead object
        Mapping_Object__mdt mappingObject = createMappingObject('', 'Id', 'Lead');
        // Create the lead fields mapping objects        
        List<Mapping_Field__mdt> mappingFields = new List<Mapping_Field__mdt>();
		mappingFields.add(createMappingField('xxx', 'xxx', ''));
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);
        
        return mappingObjects;
    }
        
    // Create Lead mapping object and fields custom metadata in memory for testing
    // This mapping is linked to the payload: Import_TestPayloadDataFactory.jsonPayload
    public static List<Mapping_Object__mdt> createLeadMappingObjectsAndFields_JSON(){
        List<Mapping_Object__mdt> mappingObjects = new List<Mapping_Object__mdt>();

        // Create mapping for lead object
        Mapping_Object__mdt mappingObject = createMappingObject('', 'Id', 'Lead');
        // Create the lead fields mapping objects        
        List<Mapping_Field__mdt> mappingFields = new List<Mapping_Field__mdt>();
		mappingFields.add(createMappingField('LeadFirstName', 'FirstName', ''));
		mappingFields.add(createMappingField('LeadLastName', 'LastName', ''));
        mappingFields.add(createMappingField('LeadCompany', 'Company', ''));
		mappingFields.add(createMappingField('Do_Not_Call_Me', 'DoNotCall', ''));
		mappingFields.add(createMappingField('NumberOf_Employees', 'NumberOfEmployees', ''));        
        mappingFields.add(createMappingField('Revenue', 'AnnualRevenue', '')); 
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);

        // Create mapping for lead object
        mappingObject = createMappingObject('cases', 'Id', 'Case');
        // Create the lead fields mapping objects        
        mappingFields = new List<Mapping_Field__mdt>();
		mappingFields.add(createMappingField('casenumber', 'Subject', ''));
        mappingFields.add(createMappingField('Origin', 'Origin', 'Import_TestMetadataFactory.ConvertCaseOrigin'));
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);

        // Create mapping for lead object
        mappingObject = createMappingObject('Owner', 'Id', 'Event');
        // Create the lead fields mapping objects        
        mappingFields = new List<Mapping_Field__mdt>();
        mappingFields.add(createMappingField('name', 'Subject', ''));
		mappingFields.add(createMappingField('LastUpdated', 'StartDateTime', ''));
        mappingFields.add(createMappingField('LastUpdated2', 'EndDateTime', ''));
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);

        // Create mapping for lead object
        mappingObject = createMappingObject('', 'Id', 'Opportunity');
        // Create the lead fields mapping objects        
        mappingFields = new List<Mapping_Field__mdt>();
        mappingFields.add(createMappingField('NumberOf_Employees', 'TotalOpportunityQuantity', ''));
		mappingFields.add(createMappingField('Transferred', 'CloseDate', ''));
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);
        
        return mappingObjects;
    }

    // Create Lead mapping object and fields custom metadata in memory for testing
    // This mapping is linked to the payload: Import_TestPayloadDataFactory.xmlPayload
    public static List<Mapping_Object__mdt> createLeadMappingObjectsAndFields_XML(){
        List<Mapping_Object__mdt> mappingObjects = new List<Mapping_Object__mdt>();

        // Create mapping for lead object
        Mapping_Object__mdt mappingObject = createMappingObject('/message', 'Id', 'Lead');
        // Create the lead fields mapping objects        
        List<Mapping_Field__mdt> mappingFields = new List<Mapping_Field__mdt>();
		mappingFields.add(createMappingField('Name', 'FirstName', ''));
		mappingFields.add(createMappingField('lastname', 'LastName', ''));
        mappingFields.add(createMappingField('Name', 'Company', ''));
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);

        // Create mapping for lead object
        mappingObject = createMappingObject('/message/cases/*', 'Id', 'Case');
        // Create the lead fields mapping objects        
        mappingFields = new List<Mapping_Field__mdt>();
		mappingFields.add(createMappingField('caseNumber', 'Subject', ''));
        mappingFields.add(createMappingField('Origin', 'Origin', 'Import_TestMetadataFactory.ConvertCaseOrigin'));
        // Join the parent and the children
        mappingObject = connectChildrenToParent(mappingObject, mappingFields);
        mappingObjects.add(mappingObject);
        
        return mappingObjects;
    }

    // Create an in memory custom metadata witha child relationship  
    private static Mapping_Object__mdt connectChildrenToParent(Mapping_Object__mdt parent, List<Mapping_Field__mdt> children){
        String parentJson = JSON.serialize(parent); 
        String childrenJson = '"IntServ__Mapping_Fields__r" : {' +
            '"totalSize" : ' + children.size() + ',' +
            '"done" : true,' + 
            '"records" : ' + JSON.serialize(children) +
            '}';
        parentJson = parentJson.substring(0, parentJson.length()-1) + ',' + childrenJson + '}';
    
        return (Mapping_Object__mdt) JSON.deserialize(parentJson, Mapping_Object__mdt.class);
    }

    private static Mapping_Object__mdt createMappingObject(string messagePayloadNode, string salesforceExternalIdField, string salesforceObject){
        Mapping_Object__mdt mappingObject = new Mapping_Object__mdt();
        mappingObject.Active__c = true;
        mappingObject.Message_Payload_Node__c = messagePayloadNode;
        mappingObject.Message_Type__c = 'TestType';
        mappingObject.Salesforce_External_Id_Field__c = salesforceExternalIdField;
        mappingObject.Salesforce_Object__c = salesforceObject;
        return mappingObject;
    }

    private static Mapping_Field__mdt createMappingField(string messagePayloadNode, string salesforceField, string transformationClassName){
        Mapping_Field__mdt mappingField = new Mapping_Field__mdt();
        mappingField.Active__c = true;
        mappingField.Message_Payload_Node__c = messagePayloadNode;
        mappingField.Salesforce_Field__c = salesforceField;
        mappingField.Transformation_Classname__c = transformationClassName;
        return mappingField;
    }
}