mdapi-source/updated-package/objects/API_Routing__mdt.object
<CustomObject>
    <description>This metadata defines what URLs can be called and what class will process the request posted to that URL</description>
    <label>API Routing</label>
    <pluralLabel>API Routings</pluralLabel>
    <fields>
        <fullName>API_URL__c</fullName>
        <description>Defines the API URL that can called by an external application.
The format is the defined base URL for the Apex REST API (for example /apigateway/v1/) + a specific destination like import.
Put together the value would be: /apigateway/v1/import</description>
        <label>API URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the route is active or not. When inactive the route will not be checked.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Http_Method__c</fullName>
        <description>The Http method that can be used with the API URL</description>
        <label>Http Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DELETE</fullName>
                    <default>true</default>
                    <label>DELETE</label>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Classname__c</fullName>
        <description>This field contains the classname of the class that will process the import message that is received at this url.
The class needs to import the Import_Service_Base class.</description>
        <label>Service Classname</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/API_ServiceFactory.cls
public class API_ServiceFactory {
    
    private static final string baseUrlMapping = '/apigateway/v1/';
    
    @testVisible 
    private static List<API_Routing__mdt> apiRoutings{
        get{ 
            if(apiRoutings == NULL){ 
                apiRoutings = [SELECT API_URL__c, Service_Classname__c, Http_Method__c 
                              FROM API_Routing__mdt 
                              WHERE Active__c = true]; 
            } 
            return apiRoutings; 
		} 
		set; 
	} 
    
    // Create the service that will process the message that is send to a specif endpoint
    public static IAPI_Service createService(RestRequest request) {          
        // Check for all active routings if the URL exsists
        for(API_Routing__mdt route : apiRoutings) {
            if (route.Http_Method__c == request.httpMethod &&
                route.API_URL__c == request.requestURI) {
                return (IAPI_Service) Type.forName(route.Service_Classname__c).newInstance();
            }
        } 

        throw new Import_Exceptions.API_Exception('Route not found');
    }
}