mdapi-source/updated-package/objects/Import_Log__c.object
<CustomObject>
    <description>This object has a master detail with Import_Message__c and displays all log files that were generated when processing the import message.</description>
    <label>Import Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Import_Finished_DateTime__c</fullName>
        <description>The date time that the processing of the import message finished.</description>
        <label>Import Finished DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Import_Is_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field displays true if the processing of the import message was successful. If any error occured, this field shows false.</description>
        <label>Import Is Successful</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Import_Log__c</fullName>
        <description>This field displays the log messages generated during the processing of the import message.</description>
        <label>Import Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Import_Message__c</fullName>
        <description>This field links to Import_Message__c where this Import_Log__c is for.</description>
        <label>Import</label>
        <referenceTo>Import_Message__c</referenceTo>
        <relationshipLabel>Import Logs</relationshipLabel>
        <relationshipName>Import_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Import_Started_DateTime__c</fullName>
        <description>The date time that the processing of the import message started.</description>
        <label>Import Started DateTime</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Import_LogMessage_DataFactory_Test.cls
@Istest
public class Import_LogMessage_DataFactory_Test {
    
    // Create one log message for each import object
    // All log fields will get the status: logFileStatus
    public static List<Import_Log__c> create_one_ImportLogObject(List<Import_Message__c> importObjects, boolean logFileStatus) {

        List<Import_Log__c> importLogObjects = new List<Import_Log__c>();
        for (Import_Message__c importObject : importObjects) {
            Import_Log__c importLogObject = new Import_Log__c();
            importLogObject.Import_Message__c = importObject.Id;
            importLogObject.Import_Started_DateTime__c = DateTime.now().addMinutes(-2);
            importLogObject.Import_Finished_DateTime__c = DateTime.now().addMinutes(-1);
            importLogObject.Import_Log__c = 'Done';
            importLogObject.Import_Is_Successful__c = logFileStatus;
            importLogObjects.add(importLogObject);
        }
        insert importLogObjects;
        
        return importLogObjects;
    }
    
    // Create two log message for each import object
    // The parameter latestLogFileStatus indicates the status of the latest log file. 
    // The second log file will get the opposite status
    public static List<Import_Log__c> create_two_ImportLogObject(List<Import_Message__c> importObjects, boolean latestLogFileStatus) {
            
        List<Import_Log__c> importLogObjects = new List<Import_Log__c>();
        for (Import_Message__c importObject : importObjects) {
            Import_Log__c importLogObject = new Import_Log__c();
            importLogObject.Import_Message__c = importObject.Id;
            importLogObject.Import_Started_DateTime__c = DateTime.now().addMinutes(-4);
            importLogObject.Import_Finished_DateTime__c = DateTime.now().addMinutes(-3);
            importLogObject.Import_Log__c = 'Done';
            importLogObject.Import_Is_Successful__c = !latestLogFileStatus;
            importLogObjects.add(importLogObject);

            importLogObject = new Import_Log__c();
            importLogObject.Import_Message__c = importObject.Id;
            importLogObject.Import_Started_DateTime__c = DateTime.now().addMinutes(-2);
            importLogObject.Import_Finished_DateTime__c = DateTime.now().addMinutes(-1);
            importLogObject.Import_Log__c = 'Done';
            importLogObject.Import_Is_Successful__c = latestLogFileStatus;
            importLogObjects.add(importLogObject);
        }
        insert importLogObjects;
        
        return importLogObjects;
    } 
}