mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.
TestType is used for unit tests</description>
        <label>Message Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type1</fullName>
                </value>
                <value>
                    <fullName>Type2</fullName>
                </value>
                <value>
                    <fullName>Test_Type</fullName>
                </value>
                <value>
                    <fullName>TEST_TYPE_TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Object__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in an import message will be mapped to what Salesforce object.</description>
    <label>Mapping Object</label>
    <pluralLabel>Mapping Objects</pluralLabel>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.</description>
        <label>Message Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/classes/Import_Mapping_Test.cls
@IsTest
public class Import_Mapping_Test {

    // Test that an exception is thrown when no mappings are found
    // The test is looking for mapping objects with the type: 'Test_Type' 
    // because of the Test_Type in the import message but no mapping records are created
    //@IsTest
    static void no_Mappings_Test(){
        // Create an import message
        List<Import_Message__c> importMessages = Import_ImportMessage_DataFactory_Test.create_ImportObject(Import_Payload_DataFactory_Test.xmlPayload);
        boolean exceptionThrown = false;
        try{
            // Get the mappings for the message type
            importMessages[0].Message_Type__c = 'TYPE_DOES_NOT_EXIST';
            Import_Mapping.getMappings(importMessages[0]);
        }
        catch (Exception e){
            exceptionThrown = true;
        }
        
        System.assert(exceptionThrown, 'Exception should be thrown');
    }
    
    // Test that the mapping data is returned
    @IsTest
    static void return_Mappings_Test(){
        // Create the mapping data in memory as records cannot be created during a unit test
        Import_Mapping.mappingObjectsMDT = Import_Metadata_DataFactory_XML_Test.createLeadMappingObjectsAndFields();
        // Prevent querying mapping objects and use the provided mapping objects
        Import_Mapping.currentMessageType = 'Test_Type'; 
            
        // Create an import message
        List<Import_Message__c> importMessages = Import_ImportMessage_DataFactory_Test.create_ImportObject(Import_Payload_DataFactory_Test.xmlPayload);
        boolean exceptionThrown = false;
        try{
            // Get the mappings for the message type
            List<Mapping_Object__mdt> objectMappings = Import_Mapping.getMappings(importMessages[0]);
            System.assert(objectMappings.size() == 2, '2 mapping object should be returned. Actual ' + objectMappings.size());
        }
        catch (Exception e){
            exceptionThrown = true;
        }
        
        System.assert(!exceptionThrown, 'No Exception should be thrown');        
    }
}