mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message_Payload__c</fullName>
        <description>The payload contains the actual data that will be loaded into Salesforce objects and fields</description>
        <label>Message Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Field__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in a section of an import message will be mapped to what Salesforce field.</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
    <fields>
        <fullName>Is_Collection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the node is a collection of values</description>
        <label>Is Collection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapping_Object__c</fullName>
        <label>Mapping Object</label>
        <referenceTo>Mapping_Object__mdt</referenceTo>
        <relationshipLabel>Mapping Fields</relationshipLabel>
        <relationshipName>Mapping_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field contains the node in the import message that will be saved in Salesforce</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <description>This field contains the Salesforce field where the node will be saved.</description>
        <label>Salesforce Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transformation_Classname__c</fullName>
        <description>This field contains the classname of the class that will transform a field from the import message payload.
The class needs to import the interface Import_Field_Transformation_Interface.</description>
        <label>Transformation Classname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Object__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in an import message will be mapped to what Salesforce object.</description>
    <label>Mapping Object</label>
    <pluralLabel>Mapping Objects</pluralLabel>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field maps a node that contains sub node(s) to a Salesforce object</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>This field  shows that what Salesforce object the Message Payload Node will be mapped</description>
        <label>Salesforce Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Import_JSON_Service.cls
public class Import_JSON_Service extends Import_Service_Base {
    
    // Import a JSON file
    @TestVisible
    private List<sObject> processRecord(Import_Message__c importMessage){
        // Convert the import message JSON payload into an object
        Object mainJSONObject = JSON.deserializeUntyped(importMessage.Message_Payload__c);
        // Get all mappings for the import message and process the JSON for each mapping object
        List<sObject> targetObjectsToSave = new List<sObject>();
        for (Mapping_Object__mdt mappingObject : Import_Mapping.getMappings(importMessage)){
            // Get all objects from the JSON based on the payload node.
            // Normally 1 object is returned but with root.cases an array of cases is returned  
            List<Object> jsonObjects = find(mainJSONObject, mappingObject.Message_Payload_Node__c);
            // Transform each object based on the mapping objects
            for (Object jsonObject : jsonObjects){
                sObject objectToSave = mapJSONToObject(mappingObject, (Map<String, Object>)jsonObject);
                // If fields on the object where updated
                if (objectToSave != null){
                    targetObjectsToSave.add(objectToSave);
                }
            }
        }
        
        return targetObjectsToSave;
    }
    
    // Based on the mapping objects and fields, create a Salesforce object based on the import message payload
    private static sObject mapJSONToObject(Mapping_Object__mdt mappingObject, Map<String, Object> jsonObject){
        // Create the target Salesforce object
        Schema.SObjectType targetSalesforceObjectType = Schema.getGlobalDescribe().get(mappingObject.Salesforce_Object__c);
		Schema.DescribeSObjectResult targetObjectDescription = targetSalesforceObjectType.getDescribe();
        sObject targetSalesforceObjectInstance = targetSalesforceObjectType.newSObject();

        // Loop through all the field mappings
        for(Mapping_Field__mdt fieldMapping : mappingObject.Mapping_Fields__r){
            Object value = jsonObject.get(fieldMapping.Message_Payload_Node__c);
			// Convert the value to the correct type
			Object typedValue = Import_Mapping_Utility.convertToSalesforceFieldType(targetSalesforceObjectType, fieldMapping, value);
            targetSalesforceObjectInstance.put(fieldMapping.Salesforce_Field__c, typedValue); 
        
            // Is_Collection__c 
        	// Transformation_Classname__c 
        }    
        
        // If no field have changed on the object Then return null
        if (targetSalesforceObjectInstance == targetSalesforceObjectType.newSObject()){
            return null;
        }

        return targetSalesforceObjectInstance;
    }

    // Get the object node from the main JSON object and
    // return the found object or a list of objects
    private List<Object> find(Object mainJSONObject, String rootNode){
        List<Object> objectsToReturn = new List<Object>();
        Object foundJSONObject = ((Map<String, Object>)mainJSONObject).get(rootNode);
		// If the mapping object node was not found retrun the main node as an object or a list of objects
        if (foundJSONObject == null){
            foundJSONObject = mainJSONObject;
        }

        // Map the mapping node to an object or list
        // Example: Mapping object node = cases,  JSON is {"name":"Jason"}
        // Returned: {"name":"Jason"}
        // Example: Mapping object node = cases,  JSON is {"name":"Jason", "cases": [{"name":"Jason"}]}
        // Returned: [{"name":"Jason"}]        
        if (foundJSONObject instanceof List<Object>) {
            objectsToReturn = (List<Object>) foundJSONObject;
        }
        else {
            objectsToReturn.add(foundJSONObject);
        }            
                
        return objectsToReturn;
    }
}