mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message_Payload__c</fullName>
        <description>The payload contains the actual data that will be loaded into Salesforce objects and fields</description>
        <label>Message Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Field__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in a section of an import message will be mapped to what Salesforce field.</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
    <fields>
        <fullName>Mapping_Object__c</fullName>
        <label>Mapping Object</label>
        <referenceTo>Mapping_Object__mdt</referenceTo>
        <relationshipLabel>Mapping Fields</relationshipLabel>
        <relationshipName>Mapping_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field contains the node in the import message that will be saved in Salesforce</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <description>This field contains the Salesforce field where the node will be saved.</description>
        <label>Salesforce Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Object__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in an import message will be mapped to what Salesforce object.</description>
    <label>Mapping Object</label>
    <pluralLabel>Mapping Objects</pluralLabel>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field maps a node that contains sub node(s) to a Salesforce object</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>This field  shows that what Salesforce object the Message Payload Node will be mapped</description>
        <label>Salesforce Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Import_XML_Service.cls
public with sharing class Import_XML_Service extends Import_Service_Base {
    
    private XPath xmlUtiltiy;
    
    // Import an XML file
    @TestVisible
    private List<sObject> processRecord(Import_Message__c importMessage){
        // Load the XML payload into the XML utility
        xmlUtiltiy = new XPath(importMessage.Message_Payload__c);
        // Get all mappings for the import message and process the XML for each mapping object
        List<sObject> targetObjectsToSave = new List<sObject>();
        for (Mapping_Object__mdt mappingObject : Import_Mapping.getMappings(importMessage)){
            // Get all objects from the XML based on the payload node.
            // The specified root node can be 1 object or a collection of objects  
            Dom.XmlNode[] xmlValues = xmlUtiltiy.find(mappingObject.Message_Payload_Node__c);
            // Transform each object based on the mapping objects 
            for (Dom.XmlNode xmlNode : xmlValues){
                sObject objectToSave = mapXMLToObject(mappingObject, xmlNode);
                // If fields on the object where updated
                if (objectToSave != null){
                    targetObjectsToSave.add(objectToSave);
                }
            }            
        }
        
        return targetObjectsToSave;
    }
    
    // Based on the mapping objects and fields, create a Salesforce object based on the import message payload
    private sObject mapXMLToObject(Mapping_Object__mdt mappingObject, Dom.XmlNode xmlNode) {

        Schema.SObjectType targetSalesforceObjectType = Schema.getGlobalDescribe().get(mappingObject.Salesforce_Object__c);
        sObject targetSalesforceObjectInstance = targetSalesforceObjectType.newSObject();

        // Loop through all the mappings for the target object
        for(Mapping_Field__mdt fieldMapping : mappingObject.Mapping_Fields__r){
            Dom.XmlNode[] nodes = xmlUtiltiy.find(xmlNode, fieldMapping.Message_Payload_Node__c);
            // Only 1 or none should be found. Otherwise goto the next node
            if (nodes.size() != 1){ 
                continue;
            }
            
            Object value = getValue(fieldMapping, nodes, targetSalesforceObjectType);
			targetSalesforceObjectInstance.put(fieldMapping.Salesforce_Field__c, value);                 
        }
        
        // If nothing has been updated on the object then return null 
        // so that the unchanged object is not added to the list of objects that will be saved.
        if (targetSalesforceObjectInstance == targetSalesforceObjectType.newSObject()){
            return null;
        }
        
        return targetSalesforceObjectInstance;
    }
    
    // Get the value from the node
    // If the node is a colltion of values then concatenate the values
    private Object getValue(Mapping_Field__mdt fieldMapping, Dom.XmlNode[] nodes, Schema.SObjectType targetSalesforceObjectType){
        Object value;
        // If not a collection then transform the single field
        if (!fieldMapping.IntServ__Is_Collection__c){
            string xmlValue = xmlUtiltiy.getText(nodes[0], fieldMapping.Message_Payload_Node__c);    
            // Convert the value to the correct type
            value = Import_Mapping_Utility.convertToSalesforceFieldType(targetSalesforceObjectType, fieldMapping, xmlValue);
        }
        else { // the node contains a list of value
            String collectionValues = '';  
            // Get all value elements from the node               
            for (Dom.XmlNode xmlValueNode : nodes[0].getChildren()){
                if (xmlValueNode.getName() == 'Value'){
                    collectionValues += String.isNotBlank(collectionValues) ? ';' : '';
                    collectionValues += xmlValueNode.getText();                                
                }
            }
            value = collectionValues;
        }
        return value;
    }
}