mdapi-source/updated-package/objects/Import_Log__c.object
<CustomObject>
    <description>This object has a master detail with Import_Message__c and displays all log files that were generated when processing the import message.</description>
    <label>Import Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Import_Finished_DateTime__c</fullName>
        <description>The date time that the processing of the import message finished.</description>
        <label>Import Finished DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Import_Is_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field displays true if the processing of the import message was successful. If any error occured, this field shows false.</description>
        <label>Import Is Successful</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Import_Log__c</fullName>
        <description>This field displays the log messages generated during the processing of the import message.</description>
        <label>Import Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Import_Message__c</fullName>
        <description>This field links to Import_Message__c where this Import_Log__c is for.</description>
        <label>Import</label>
        <referenceTo>Import_Message__c</referenceTo>
        <relationshipLabel>Import Logs</relationshipLabel>
        <relationshipName>Import_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Import_Started_DateTime__c</fullName>
        <description>The date time that the processing of the import message started.</description>
        <label>Import Started DateTime</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Import_Logging.cls
public with sharing class Import_Logging {

    public Import_Log__c importLogObject;

    // Constructor
    public Import_Logging(Import_Message__c importMessage){
        importLogObject = new Import_Log__c();
        importLogObject.Import_Started_DateTime__c = datetime.now();
        importLogObject.Import_Is_Successful__c = false;
        importLogObject.Import_Log__c = '';
        importLogObject.Import_Message__c = importMessage.Id;
    }
        
    // Log success when no unexpected excpetions occured
    // Although the overall processing did not throw an exception
    // the Import_Is_Successful__c might still be false if not all
    // objects were saved successfully
    public void logSuccess(Database.UpsertResult[] saveResults, list<sObject> recordsToSave){
		logSaveResult(saveResults, recordsToSave);
        importLogObject.Import_Finished_DateTime__c = datetime.now();        
    }

	// Log failure when an unexpected excpetion occured
    public void logError(Exception e){
        // Create the response JSON
        API_Response errorResponse = new API_Response();
        errorResponse.createUnhandledExcpetionResponse(e.getMessage());
        
        importLogObject.Import_Log__c += JSON.serialize(errorResponse) + '\n';
        importLogObject.Import_Log__c += e.getStackTraceString() + '\n';
        importLogObject.Import_Is_Successful__c = false;
        importLogObject.Import_Finished_DateTime__c = datetime.now();
    }    
    
    // Loop through the upsert results and save the messages
    private void logSaveResult(Database.UpsertResult[] saveResults, list<sObject> recordsToSave){
        // Create the response JSON
        API_Response apiRepsonse = new API_Response();
        
        if (saveResults.size() == 0){
            apiRepsonse.response.status = 'NOCHANGES';
            importLogObject.Import_Log__c = JSON.serialize(apiRepsonse);
            return;
        }
        
        // Loop through the upsert results
        for(Integer index = 0; index < saveResults.size(); index++) {  
          	API_Response.ResultObject resultObject = getObjectMessage(saveResults[index], recordsToSave[index]);
            // Find the save record
            if(saveResults[index].isSuccess()) {
                apiRepsonse.response.results.add(resultObject);
            }
            else {
                // Operation failed, so get all errors
                API_Response.ErrorObject errorObject = getErrorMessages(saveResults[index], recordsToSave[index]);
                apiRepsonse.response.errors.add(errorObject);
                apiRepsonse.response.errorsize = apiRepsonse.response.errors.size();   
            }
        }
        
        importLogObject.Import_Is_Successful__c = (apiRepsonse.response.errorsize == 0) ? true : false;    
        importLogObject.Import_Log__c += JSON.serialize(apiRepsonse);
    }
    
    // Create the error messages
    private API_Response.ErrorObject getErrorMessages(Database.UpsertResult saveResult, sObject saveObject){
        // Operation failed, so get all errors
        API_Response.ErrorObject errorObject = new API_Response.ErrorObject();
        errorObject.salesforceobjecttype = String.valueOf(saveObject.getSObjectType());
        errorObject.id = saveResult.getId();
        
        List<String> errors = new List<String>();
        // Operation failed, so get all errors
        for(Database.Error err : saveResult.getErrors()) {
            errors.add('", Error for field: ' + err.getFields() + ', Error message: "' + err.getMessage() + '".');   
        }
        errorObject.message = String.join(errors, ' ');
		return errorObject;        
    }
    
    // Create the success massage
    private API_Response.ResultObject getObjectMessage(Database.UpsertResult saveResult, sObject saveObject){
        API_Response.ResultObject resulObject = new API_Response.ResultObject();
        resulObject.salesforceobjecttype = String.valueOf(saveObject.getSObjectType());
        resulObject.id = saveResult.getId();
        if(saveResult.isCreated()) {
            resulObject.operation = 'CREATED';
        } else {
            resulObject.operation = 'UPDATED';
        }    
        return resulObject;
    }
}