mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.
TestType is used for unit tests</description>
        <label>Message Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type1</fullName>
                </value>
                <value>
                    <fullName>Type2</fullName>
                </value>
                <value>
                    <fullName>Test_Type</fullName>
                </value>
                <value>
                    <fullName>TEST_TYPE_TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Field__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in a section of an import message will be mapped to what Salesforce field.</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the mapping will be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Collection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the node is a collection of values</description>
        <label>Is Collection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapping_Object__c</fullName>
        <label>Mapping Object</label>
        <referenceTo>Mapping_Object__mdt</referenceTo>
        <relationshipLabel>Mapping Fields</relationshipLabel>
        <relationshipName>Mapping_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field contains the node in the import message that will be saved in Salesforce</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <description>This field contains the Salesforce field where the node will be saved.</description>
        <label>Salesforce Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transformation_Classname__c</fullName>
        <description>This field contains the classname of the class that will transform a field from the import message payload.
The class needs to import the interface Import_Field_Transformation_Interface.</description>
        <label>Transformation Classname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Object__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in an import message will be mapped to what Salesforce object.</description>
    <label>Mapping Object</label>
    <pluralLabel>Mapping Objects</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the mapping will be used</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field maps a node that contains sub node(s) to a Salesforce object</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.</description>
        <label>Message Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_External_Id_Field__c</fullName>
        <description>The name of the external id field that needs to be used when doing the upsert.</description>
        <label>Salesforce External Id Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>This field  shows that what Salesforce object the Message Payload Node will be mapped</description>
        <label>Salesforce Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Import_Mapping.cls
public class Import_Mapping {

    @TestVisible
    private static List<Mapping_Object__mdt> mappingObjectsMDT;
    @TestVisible
    private static string currentMessageType;
    
    // Get the mapping objects and related mapping fields
	public static List<Mapping_Object__mdt> getMappings(Import_Message__c importMessage){ 
        
        // If the mappings for the current import message type are not loaded 
        // Then retrieve the mappings for the message type
        if (currentMessageType != importMessage.Message_Type__c){
            currentMessageType = importMessage.Message_Type__c;        
			mappingObjectsMDT = 
                [SELECT
                    Message_Payload_Node__c,
                    Salesforce_Object__c,
                    Salesforce_External_Id_Field__c,
                    (SELECT Message_Payload_Node__c, Salesforce_Field__c, 
                       Is_Collection__c, Transformation_Classname__c
                    FROM Mapping_Fields__r
                    WHERE Active__c = true)
                 FROM 
                    Mapping_Object__mdt 
                 WHERE 
                    Active__c = true AND
                    Message_Type__c = :importMessage.Message_Type__c
                 Order By
                 	Salesforce_Object__c];
        } 
        
        // Throw error if no mapping records are found
        if (mappingObjectsMDT.size() == 0){
            throw new Import_Exceptions.Mapping_Exception('No mapping records found');             
        }

        return mappingObjectsMDT;
    } 
}