mdapi-source/updated-package/objects/Import_Message__c.object
<CustomObject>
    <description>This object will hold all the integration messages that are received by the Apex REST API.
The fields will contain general information about the message and the actual payload (data to add to Salesforce).
Related to this object are log messages that show the status of the processing of the integration message.</description>
    <label>Import Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message_Payload__c</fullName>
        <description>The payload contains the actual data that will be loaded into Salesforce objects and fields</description>
        <label>Message Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message_Source_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is an identifier (normally some kind of GUID) from the source system that can link the message in Salesforce to a message in the source system</description>
        <externalId>true</externalId>
        <label>Message Source Id</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Message_Source_System__c</fullName>
        <description>This is the name of the source system.</description>
        <label>Message Source System</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.
TestType is used for unit tests</description>
        <label>Message Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type1</fullName>
                </value>
                <value>
                    <fullName>Type2</fullName>
                </value>
                <value>
                    <fullName>Test_Type</fullName>
                </value>
                <value>
                    <fullName>TEST_TYPE_TEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Import_TestMessageDataFactory.cls
@IsTest
public class Import_TestMessageDataFactory {

    // Create the body that can be added to an API call
    public static string apiBody(string payload) {
        // Check if the payload is JSON
        boolean isJSONValid = true; 
        try {
            // Check if the URL body is JSON
            JSON.deserializeUntyped(payload);
        } 
        catch (Exception e) {
            isJSONValid = false;
        }
        // If the payload is JSON escape the " character. This is needed
        // because the payload field is treated as a string so that it can 
        // conatin multiple formats
        if (isJSONValid){
            payload = payload.replace('"', '\\"');
        }
        
    	string urlBody = 
            '{"records":' +
            '  [{' +
            '    "Message_Payload__c":"' + payload + '",' +
            '    "Message_Source_Id__c":"fdeab5f5-75f1-4875-b0d8-b193e4ebf330",' +
            '    "Message_Source_System__c":"System1",' +
            '    "Message_Type__c":"TestType"' +
            '  }]' +
            '}';       
        return urlBody;
    }
   
    // Create basic import objects
    public static List<Import_Message__c> create_ImportObject(string payload){
        
        List<Import_Message__c> importMessages = new List<Import_Message__c>();        
        Import_Message__c importMessage = new Import_Message__c();
        importMessage.Message_Payload__c = payload;
        importMessage.Message_Source_Id__c = 'fdeab5f5-75f1-4875-b0d8-b193e4ebf330';
        importMessage.Message_Source_System__c = 'System1';
        importMessage.Message_Type__c = 'TestType';
        importMessages.add(importMessage);
        insert importMessages;
        
        return importMessages;
    }
}