mdapi-source/updated-package/objects/Mapping_Field__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in a section of an import message will be mapped to what Salesforce field.</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
    <fields>
        <fullName>Transformation_Classname__c</fullName>
        <description>This field contains the classname of the class that will transform a field from the import message payload.
The class needs to import the interface Import_Field_Transformation_Interface.</description>
        <label>Transformation Classname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Import_Field_Transformation_Interface.cls
// Add this interface to a class and mention the transfromation class
// on the custom metadata record Mapping_Field__mdt.Transformation_Classname__c	
public interface Import_Field_Transformation_Interface {
    // When importing of a message it might be needed to transform 
    // the import message value to a Salesforce value. 
    // For example: transform country code DE to Germany. 
	Object transformValue(Object value);
}