mdapi-source/updated-package/objects/Mapping_Field__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in a section of an import message will be mapped to what Salesforce field.</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the mapping will be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Collection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the node is a collection of values</description>
        <label>Is Collection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapping_Object__c</fullName>
        <label>Mapping Object</label>
        <referenceTo>Mapping_Object__mdt</referenceTo>
        <relationshipLabel>Mapping Fields</relationshipLabel>
        <relationshipName>Mapping_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field contains the node in the import message that will be saved in Salesforce</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <description>This field contains the Salesforce field where the node will be saved.</description>
        <label>Salesforce Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transformation_Classname__c</fullName>
        <description>This field contains the classname of the class that will transform a field from the import message payload.
The class needs to import the interface Import_Field_Transformation_Interface.</description>
        <label>Transformation Classname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Mapping_Object__mdt.object
<CustomObject>
    <description>This custom metadata contains what element in an import message will be mapped to what Salesforce object.</description>
    <label>Mapping Object</label>
    <pluralLabel>Mapping Objects</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the mapping will be used</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Payload_Node__c</fullName>
        <description>This field maps a node that contains sub node(s) to a Salesforce object</description>
        <label>Message Payload Node</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>With this field you can process messages in different ways. This value defines how the import logic is being processed.</description>
        <label>Message Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_External_Id_Field__c</fullName>
        <description>The name of the external id field that needs to be used when doing the upsert.</description>
        <label>Salesforce External Id Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>This field  shows that what Salesforce object the Message Payload Node will be mapped</description>
        <label>Salesforce Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/classes/Import_Metadata_DataFactory_Utility_Test.cls
@IsTest
public class Import_Metadata_DataFactory_Utility_Test {
    
    // Create an in memory custom metadata with a child relationship  
    public static Mapping_Object__mdt connectChildrenToParent(Mapping_Object__mdt parent, List<Mapping_Field__mdt> children){
        String parentJson = JSON.serialize(parent); 
        String childrenJson = '"IntServ__Mapping_Fields__r" : {' +
            '"totalSize" : ' + children.size() + ',' +
            '"done" : true,' + 
            '"records" : ' + JSON.serialize(children) +
            '}';
        parentJson = parentJson.substring(0, parentJson.length()-1) + ',' + childrenJson + '}';
        return (Mapping_Object__mdt) JSON.deserialize(parentJson, Mapping_Object__mdt.class);
    }

    // Create an in memory custom metadata object mapping
    public static Mapping_Object__mdt createMappingObject(string messagePayloadNode, string salesforceExternalIdField, string salesforceObject){
        Mapping_Object__mdt mappingObject = new Mapping_Object__mdt();
        mappingObject.Active__c = true;
        mappingObject.Message_Payload_Node__c = messagePayloadNode;
        mappingObject.Message_Type__c = 'Test_Type';
        mappingObject.Salesforce_External_Id_Field__c = salesforceExternalIdField;
        mappingObject.Salesforce_Object__c = salesforceObject;
        return mappingObject;
    }

    // Create an in memory custom metadata field mapping
    public static Mapping_Field__mdt createMappingField(string messagePayloadNode, string salesforceField, 
                                                        string transformationClassName, boolean isCollection){
        Mapping_Field__mdt mappingField = new Mapping_Field__mdt();
        mappingField.Active__c = true;
        mappingField.Message_Payload_Node__c = messagePayloadNode;
        mappingField.Salesforce_Field__c = salesforceField;
        mappingField.Transformation_Classname__c = transformationClassName;
        mappingField.Is_Collection__c = isCollection;
        return mappingField;
    }
}